# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-22 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='category',
            field=models.CharField(max_length=80),
        ),
    ]
