# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-25 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_auto_20160522_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dates',
            old_name='count',
            new_name='vote',
        ),
    ]
